Accept TRUENAS-MINI as well as FREENAS-MINI for enclosure
freenas/freenas pull request #5632
Opened 2020-09-08 19:33 UTC by william-gr

Ticket:	NAS-107492

2020-09-08 19:44 UTC, themylogin requested changes

2020-09-08 19:44 UTC, themylogin commented on src/freenas/usr/local/lib/middlewared_truenas/plugins/enclosure_/map.py
> +    ProductMapping(re.compile(r"(TRUE|FREE)-MINI-3.0-XL\+$"), [
You've forgot NAS here

2020-09-08 19:46 UTC, william-gr commented on src/freenas/usr/local/lib/middlewared_truenas/plugins/enclosure_/map.py
> +    ProductMapping(re.compile(r"(TRUE|FREE)-MINI-3.0-XL\+$"), [
Good catch, updated

2020-09-08 19:46 UTC, themylogin approved these changes

2020-09-08 19:50 UTC, merged

2020-09-09 12:29 UTC, william-gr commented
backport