Enforce 1GiB limit on cores dataset
freenas/freenas pull request #5688
Opened 2020-09-18 13:43 UTC by anodos325

Destroy the cores dataset if it has > 1GiB written to it, then re-create with a 1GiB quota.

2020-09-18 14:35 UTC, yocalebo requested changes
You’re probably going to want to wrap the deletion of the cores dataset in a try/except because it routinely gets “locked” by user space applications. Particularly in the past, middlewared will try to dump 50G worth and it will go catatonic and lock it up.

2020-09-18 15:15 UTC, anodos325 commented
> You’re probably going to want to wrap the deletion of the cores dataset in a try/except because it routinely gets “locked” by user space applications. Particularly in the past, middlewared will try to dump 50G worth and it will go catatonic and lock it up.

I'll add try/except, but the situation where this code is most likely to get run is during boot just after upgrading to 12.0 (system dataset setup).

2020-09-18 15:36 UTC, yocalebo approved these changes

2020-09-18 15:55 UTC, william-gr requested changes

2020-09-18 15:55 UTC, william-gr commented on src/middlewared/middlewared/plugins/sysdataset.py
> +                    self.logger.warning("Failed to replace dataset [%].", dataset, exc_info=True)
Missing %s

2020-09-18 17:05 UTC, william-gr approved these changes

2020-09-18 17:05 UTC, merged

2020-09-21 00:29 UTC, yocalebo commented
> > You’re probably going to want to wrap the deletion of the cores dataset in a try/except because it routinely gets “locked” by user space applications. Particularly in the past, middlewared will try to dump 50G worth and it will go catatonic and lock it up.
> 
> I'll add try/except, but the situation where this code is most likely to get run is during boot just after upgrading to 12.0 (system dataset setup).

pretty sure this runs when (not positive):
1. fresh HA system and the 1st zpool is created (we auto migrate the system dataset to zpool)
2. restart middlewared from CLI