add glustereventsd service api
freenas/freenas pull request #5709
Opened 2020-09-22 17:54 UTC by yocalebo

2020-09-22 18:01 UTC, themylogin requested changes

2020-09-22 18:01 UTC, themylogin commented on src/middlewared/middlewared/plugins/gluster_linux/eventsd.py
> +        if len(self.URLS) == 5:
What if there are 6?

2020-09-22 18:01 UTC, themylogin commented on src/middlewared/middlewared/plugins/gluster_linux/eventsd.py
> +                f'webhook_url_create.{data["url"]}',
Why so weird variable name?

2020-09-22 18:02 UTC, william-gr commented on src/middlewared/middlewared/plugins/gluster_linux/eventsd.py
> +        private = True
If this is a private API, what/who is going to use it?

2020-09-23 13:38 UTC, themylogin approved these changes
LGTM

2020-09-23 14:22 UTC, merged