ES24f and ES102 support
freenas/freenas pull request #5830
Opened 2020-10-14 15:43 UTC by themylogin

2020-10-14 15:45 UTC, darkfiberiru commented
Looks good for es24f but doesn't seem to include es102 yet as indicated in PR

2020-10-14 15:47 UTC, darkfiberiru approved these changes
Looks good to me. All ses details for slots will be passed 1 to 1 via api?

2020-10-14 15:49 UTC, william-gr approved these changes

2020-10-15 18:39 UTC, darkfiberiru requested changes
ES24F was correct typo in ticket. Shelves are always all caps.

2020-10-15 18:39 UTC, darkfiberiru commented on src/freenas/usr/local/lib/middlewared_truenas/alert/source/license_status.py
> -                # ES24F Expansion shelf
@themylogin This is correct as  ES24F sorry for typo in original ticket. This is via Andrew Nyguen Product PM who caught my mistake in ticket

2020-10-16 19:07 UTC, darkfiberiru approved these changes
Looks good now thank you

2020-10-16 20:01 UTC, merged