Only send usage stats for master node
freenas/freenas pull request #5902
Opened 2020-10-23 10:26 UTC by sonicaj

2020-10-25 12:34 UTC, yocalebo approved these changes

2020-10-26 14:16 UTC, william-gr requested changes

2020-10-26 14:16 UTC, william-gr commented on src/middlewared/middlewared/plugins/usage.py
> +                await self.middleware.call('failover.is_backup_node') or not await self.middleware.call(
failover.status not in ('SINGLE', "MASTER')

2020-10-26 16:02 UTC, william-gr approved these changes

2020-10-26 16:41 UTC, merged

2020-10-26 16:43 UTC, sonicaj commented
backport