R-Series support in enclosure API
freenas/freenas pull request #5974
Opened 2020-11-04 21:57 UTC by themylogin

For R10 and R20 we'll get one enclosure

For R40 we'll get two enclosures: `R40, Drawers #1-2` and `R40, Drawers #3-4` (I've invented the names, please let me know if I am wrong). They were named the same (`ECStream FS2 c209`) so I guess I order them by appearance order in `/dev/ses*`?

For R50 we'll get two enclosures too: `R50, Drawer #1` and `R50, Drawer #2`, the number I can get from the name

2020-11-05 13:04 UTC, william-gr commented
Code looks fine to me but I am unsure about the Drawer thing, I will let @darkfiberiru comment if it has any sense.

2020-11-06 16:26 UTC, william-gr commented
@darkfiberiru ping

2020-11-06 18:13 UTC, darkfiberiru commented
Looking at this now

2020-11-06 18:36 UTC, darkfiberiru commented
Via NEP 24 @themylogin we would want to map the two "drawers" two a single virtual ses enclosure for the ui. These are contiguous slots on the system and we don't want to duplicate slot numbers on chassis. The R50 will also have a nvme enclosure like the nvme plx but no directly attached to motherboard.

A major point of NEP 24 is that a slot number matches a single place on the chassis even if there front/rear/top drives.

I can login to the r50 and that's clear that for enclosure management drawer 1/drawer 2 just need concatenated and then pcie devices after that.

R40 looks like both ses devices(24 drives each) just need concatenated into a single enclosure for the ui also

2020-11-06 18:38 UTC, darkfiberiru requested changes
We should give webui a single "enclosure" for the entire chassis so that all slot number are contiguous and non repeating. See notes above.

2020-11-06 20:31 UTC, themylogin commented
@darkfiberiru what about they order? Are they guaranteed to appear in `/dev/ses*` always in the same order?

2020-11-09 15:27 UTC, darkfiberiru commented
@themylogin They should always appear in same order. If they don't would be hardware(wiring) issue not software.

2020-11-09 17:51 UTC, themylogin commented
I've made it merge all `XXX, Drawer #N` enclosures into one

2020-11-09 17:59 UTC, darkfiberiru approved these changes
I think it looks good now other then full nvme details we need from R-Series PM

2020-11-10 17:55 UTC, william-gr approved these changes

2020-11-10 17:56 UTC, merged