Support SED disks in Scale
freenas/freenas pull request #6040
Opened 2020-11-19 13:36 UTC by sonicaj

2020-11-21 18:00 UTC, themylogin requested changes
Why don't you make `disk_/sed_freebsd.py` and `disk_/sed_linux.py`?

2020-11-21 18:05 UTC, sonicaj commented
Primarily because of the diff. Ideally I wanted to have sed in a separate plugin part. I can update the PR with the changes : )

2020-11-21 18:08 UTC, themylogin commented
We are not getting a good diff for this method anyway, so let's move at least this one method. For others it's probably better to stay where they are now.

2020-11-23 07:29 UTC, themylogin submitted a review, later dismissed

2020-11-23 07:29 UTC, themylogin commented on src/middlewared/middlewared/plugins/disk.py
> +                # Disk needs to be retested after unlock
It was not a typo, it's really `GEOM retaste`. Is it needed on Linux by the way?

2020-11-26 14:26 UTC, william-gr commented on src/freenas/usr/local/bin/truenas-grub.py
> +        'GRUB_CMDLINE_LINUX_DEFAULT="libata.allow_tpm=1"',
This is also possible to control via a /proc or /sys (dont remember which). Wonder if its better to keep it in t he plugin to keep it self-contained?

2020-11-27 16:39 UTC, william-gr approved these changes

2020-11-30 22:41 UTC, merged