Add validation to ensure valid mac address is provided for VM nice device
freenas/freenas pull request #6053
Opened 2020-11-21 13:51 UTC by sonicaj

2020-11-21 13:52 UTC, sonicaj commented
backport

2020-11-21 14:13 UTC, themylogin requested changes

2020-11-21 14:13 UTC, themylogin commented on src/middlewared/middlewared/plugins/vm/vm_devices.py
> +            if mac and not RE_MAC_CHECK.search(mac):
Can't we just use `MACAddr` validator on the schema field?

2020-11-21 17:58 UTC, themylogin approved these changes

2020-11-23 13:24 UTC, william-gr approved these changes

2020-11-23 17:51 UTC, merged