installer: Clarify preferred media for install
freenas/freenas pull request #6179
Opened 2020-12-17 20:55 UTC by freqlabs

"flash media" makes it sound like USB flash is OK to install to.
We do not want to recommend it.

2020-12-17 21:01 UTC, yocalebo commented
Being nit-picky but maybe say SATA, SAS or NVMe flash media.

2020-12-17 21:14 UTC, freqlabs commented
Should I discourage SATA DOMs as well?

2020-12-17 21:21 UTC, william-gr commented
SATA DOMs are not bad, the specific ones we used were, IMO

2020-12-18 14:09 UTC, yocalebo approved these changes

2020-12-18 14:10 UTC, yocalebo commented
@Mrt134 We want to make it obvious that we don't recommend installing flash usb sticks. I think this verbiage makes sense and gets the point across but would like you to give final review since you're docs 😄

2020-12-18 14:14 UTC, kmoore134 requested changes
Recommend the following wording:

Installing on SATA, SAS, or NVMe flash media is preferred. USB flash sticks are unsupported.

2020-12-18 14:23 UTC, kmoore134 commented
Ok, slight wording change after review with William:

"Installing on SATA, SAS, or NVMe flash media is recommended. USB flash sticks are discouraged."

2020-12-18 14:23 UTC, Mrt134 reviewed
Suggest we explicitly discourage USB installs as it only appears to lead to trouble and a poor customer experience. Kris' suggestion should do the trick.

2020-12-18 14:49 UTC, william-gr approved these changes

2020-12-18 14:49 UTC, merged