Make restarting attachments optional on dataset unlock
freenas/freenas pull request #6250
Opened 2021-01-09 01:18 UTC by sonicaj

2021-01-12 21:13 UTC, themylogin approved these changes

2021-01-12 21:22 UTC, yocalebo requested changes
This breaks HA systems.

`unlock_zfs_datasets` uses `toggle_attachments` in `pool.dataset.unlock`

2021-01-12 21:27 UTC, sonicaj commented
@yocalebo thank you for pointing that out. I'll fix it.

2021-01-12 23:39 UTC, pep8speaks commented
Hello @sonicaj! Thanks for updating this PR. We checked the lines you've touched for [PEP 8](https://www.python.org/dev/peps/pep-0008) issues, and found:

* In the file [`src/freenas/usr/local/lib/middlewared_truenas/plugins/failover.py`](https://github.com/freenas/freenas/blob/41eb714604113be8dff699a8f9646b63b4df3f89/src/freenas/usr/local/lib/middlewared_truenas/plugins/failover.py):

> [Line 635:3](https://github.com/freenas/freenas/blob/41eb714604113be8dff699a8f9646b63b4df3f89/src/freenas/usr/local/lib/middlewared_truenas/plugins/failover.py#L635): [E111](https://duckduckgo.com/?q=pep8%20E111) indentation is not a multiple of four
> [Line 642:3](https://github.com/freenas/freenas/blob/41eb714604113be8dff699a8f9646b63b4df3f89/src/freenas/usr/local/lib/middlewared_truenas/plugins/failover.py#L642): [E111](https://duckduckgo.com/?q=pep8%20E111) indentation is not a multiple of four

2021-01-13 12:27 UTC, yocalebo approved these changes

2021-01-14 09:11 UTC, merged

2021-01-14 16:17 UTC, william-gr commented on src/middlewared/middlewared/plugins/pool.py
> +            List('services_restart', default=[]),
Was the API change necessary? Backward incompatible API change... @sonicaj