Start/stop s3 if underlying dataset is locked/unlocked
freenas/freenas pull request #6338
Opened 2021-01-31 14:42 UTC by sonicaj

This PR introduces following changes:

1) Introduces attachment delegate for s3
2) Allows unsetting storage path for s3 service

2021-01-31 17:32 UTC, yocalebo commented on src/middlewared/middlewared/plugins/service_/services/s3.py
> +            raise CallError('Storage path must bet set to start S3 service')
```suggestion
            raise CallError('Storage path must be set to start S3 service')
```

2021-01-31 19:33 UTC, themylogin requested changes

2021-01-31 19:33 UTC, themylogin commented on src/middlewared/middlewared/plugins/s3_/attachments.py
> +            self.middleware.logger.error('Failed to start s3')
Please log this with exc_info=True, same for above

2021-01-31 19:57 UTC, themylogin requested changes

2021-01-31 19:57 UTC, themylogin commented on src/middlewared/middlewared/plugins/s3_/attachments.py
> +            self.middleware.logger.error('Failed to stop s3: %s', e, exc_info=True)
There is no need for `'%s' % e` anymore

2021-01-31 19:58 UTC, pep8speaks commented
Hello @sonicaj! Thanks for updating this PR. We checked the lines you've touched for [PEP 8](https://www.python.org/dev/peps/pep-0008) issues, and found:





* In the file [`src/middlewared/middlewared/plugins/s3_/attachments.py`](https://github.com/freenas/freenas/blob/fd3f31124f1f0e36339f8fd9e2c7eca0abcece1d/src/middlewared/middlewared/plugins/s3_/attachments.py):

> [Line 39:9](https://github.com/freenas/freenas/blob/fd3f31124f1f0e36339f8fd9e2c7eca0abcece1d/src/middlewared/middlewared/plugins/s3_/attachments.py#L39): [F841](https://duckduckgo.com/?q=pep8%20F841) local variable 'e' is assigned to but never used

2021-02-03 18:09 UTC, william-gr approved these changes

2021-02-03 18:14 UTC, themylogin approved these changes

2021-02-04 19:47 UTC, merged