handle k3s and VMs on SCALE HA appropriately
freenas/freenas pull request #6340
Opened 2021-02-01 15:05 UTC by yocalebo

- don't start VMs or k3s automatically on system event `ready` on SCALE HA systems since the failover event plugin is responsible for starting those services
- on failover master event start VMs and k3s as necessary
- fix minor `logger.info` typo when disallowing network traffic on failover backup event
- when a VM fails to start, don't log as `logger.debug` but instead use `logger.error`

2021-02-01 15:10 UTC, sonicaj requested changes
We should also stop `kubernetes` service on MASTER node when it's going to become BACKUP ?

2021-02-01 15:10 UTC, sonicaj commented on src/freenas/usr/local/lib/middlewared_truenas/plugins/failover_/event_linux.py
> +            self.run_call('service.start', 'k3s')
Please replace `k3s` with `kubernetes`

2021-02-01 15:10 UTC, sonicaj commented on src/middlewared/middlewared/plugins/vm/lifecycle.py
> +    if args['id'] == 'ready' and not await middleware.call('failover.licensed'):
We still need to initialize vms, let's please remove this condition as it's already being done below at L159

2021-02-01 15:15 UTC, yocalebo commented
> We should also stop `kubernetes` service on MASTER node when it's going to become BACKUP ?

No, I'd rather not. The BACKUP event needs to be as quick as possible. Waiting on those would cause unnecessary time to the overall failover event.

2021-02-01 15:17 UTC, yocalebo commented
> > We should also stop `kubernetes` service on MASTER node when it's going to become BACKUP ?
> 
> No, I'd rather not. The BACKUP event needs to be as quick as possible. Waiting on those would cause unnecessary time to the overall failover event.

Derp, you mean if we're able to export the zpools cleanly. (On unclean export, we forcefully reboot). So you're correct, I'll fix.

2021-02-02 09:31 UTC, sonicaj approved these changes

2021-02-02 13:32 UTC, merged